modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "interesium"
version = "${version}"
displayName = "Interesium"
authors = "TeamPotato"
description = '''
A mod that optimizes Mojang's PointOfInterests system. Concept from Lithium but extended in execution.
'''

[[dependencies.interesium]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
